"use server";

import { createClient } from "@/lib/supabase/server";
import { requireStaffContext } from "@/lib/org-context";
import { auditLog } from "@/lib/audit";
import { sendEmail, appUrl } from "@/lib/email/client";
import { invitationEmail } from "@/lib/email/templates";
import { revalidatePath } from "next/cache";
import type { OrgRole } from "@/types/database";

// ---------------------------------------------------------------------------
// Send an invitation
// ---------------------------------------------------------------------------
export async function sendInvitation(formData: FormData) {
  const ctx = await requireStaffContext();

  if (ctx.role !== "owner" && ctx.role !== "admin") {
    return { error: "Only owners and admins can invite members." };
  }

  const supabase = await createClient();
  const email = String(formData.get("email") ?? "").trim().toLowerCase();
  const role = String(formData.get("role") ?? "member") as OrgRole;

  if (!email || !email.includes("@")) {
    return { error: "A valid email address is required." };
  }

  // Check if someone with this email is already in the workspace
  // (best-effort — accept_invitation() enforces this at the DB level too)
  const { data: memberEmails } = await supabase.rpc("get_org_staff_emails", {
    p_org_id: ctx.organization.id,
  });

  const normalized = (memberEmails ?? []).map((e: string) => e.toLowerCase());
  if (normalized.includes(email)) {
    return { error: "This person is already a member of your workspace." };
  }

  // Check for pending invite to same email
  const { data: existing } = await supabase
    .from("invitations")
    .select("id")
    .eq("organization_id", ctx.organization.id)
    .eq("email", email)
    .is("accepted_at", null)
    .gte("expires_at", new Date().toISOString())
    .maybeSingle();

  if (existing) {
    return { error: "An active invitation for this email already exists." };
  }

  // Create the invitation row (token is auto-generated by the DB default)
  const { data: invitation, error: invError } = await supabase
    .from("invitations")
    .insert({
      organization_id: ctx.organization.id,
      invited_by: ctx.userId,
      email,
      role,
    })
    .select("token")
    .single();

  if (invError || !invitation) {
    return { error: invError?.message ?? "Could not create invitation." };
  }

  // Send the email
  const inviteUrl = `${appUrl()}/invite/${invitation.token}`;
  const inviterName = ctx.profile?.full_name ?? ctx.email ?? "A teammate";

  await sendEmail({
    to: email,
    ...invitationEmail({
      inviterName,
      orgName: ctx.organization.name,
      inviteUrl,
    }),
  }).then((result) => {
    if (!result) {
      console.warn("[invite] Email not sent — RESEND_API_KEY may be missing.");
    }
  });

  await auditLog({
    organizationId: ctx.organization.id,
    actorId: ctx.userId,
    action: "invite",
    resourceType: "invitation",
    resourceName: email,
    metadata: { role },
  });

  revalidatePath("/settings/invites");
  return { success: true };
}

// ---------------------------------------------------------------------------
// Accept an invitation via token (called from /invite/[token] page)
// ---------------------------------------------------------------------------
export async function acceptInvitation(token: string) {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: "You need to be signed in to accept this invitation." };

  const { data, error } = await supabase.rpc("accept_invitation", {
    p_token: token,
  });

  if (error) return { error: error.message };

  const result = data as { success?: boolean; error?: string; org_slug?: string };

  if (result?.error) return { error: result.error };

  return { success: true, orgSlug: result.org_slug as string };
}

// ---------------------------------------------------------------------------
// Revoke a pending invitation
// ---------------------------------------------------------------------------
export async function revokeInvitation(invitationId: string) {
  const ctx = await requireStaffContext();
  const supabase = await createClient();

  const { error } = await supabase
    .from("invitations")
    .delete()
    .eq("id", invitationId)
    .eq("organization_id", ctx.organization.id);

  if (error) return { error: error.message };

  revalidatePath("/settings/invites");
  return { success: true };
}
